# generated by datamodel-codegen:
#   filename:  reply_success.schema.json
#   timestamp: 2025-03-19T13:34:54+00:00

from __future__ import annotations

from typing import Dict, List, Literal, Optional
from uuid import UUID

from pydantic import BaseModel, Field, constr


class QuantumHardwareRunCircuitResult(BaseModel):
    job_id: int = Field(
        ..., description='Client defined identifier for the execution.', title='Job Id'
    )
    results: Dict[str, int] = Field(
        ...,
        description='Mapping of measured bitstring (little endian notation; q[n]...q[0]) to count of occurrences.',
        title='Results',
    )
    raw_data: Optional[List[str]] = Field(
        None,
        description='A list of bitstrings (little endian notation; `q[n]...q[0]`) ordered by the shot in which it             was measured.',
        title='Raw Data',
    )


class ExecuteReplySuccess(BaseModel):
    version: constr(pattern=r'^\d+\.\d+\.\d$') = Field(..., title='Version')
    session_id: UUID = Field(
        ...,
        description='An arbitrary string, filled in in the request, which is copied into the reply object.',
        title='Session Id',
    )
    status: Literal['success'] = Field(..., title='Status')
    payload: QuantumHardwareRunCircuitResult
