# generated by datamodel-codegen:
#   filename:  reply_failure.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, constr


class GetDynamicReplyFailure(BaseModel):
    version: constr(pattern=r'^\d+\.\d+\.\d$') = Field(..., title='Version')
    status: Literal['failure'] = Field(..., title='Status')
