# generated by datamodel-codegen:
#   filename:  request.schema.json
#   timestamp: 2025-03-19T13:34:56+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, constr


class GetStaticRequest(BaseModel):
    version: constr(pattern=r'^\d+\.\d+\.\d$') = Field(..., title='Version')
    command: Literal['get_static'] = Field(..., title='Command')
