# generated by datamodel-codegen:
#   filename:  reply_failure.schema.json
#   timestamp: 2025-03-19T13:34:55+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, constr


class GetStaticReplyFailure(BaseModel):
    version: constr(pattern=r'^\d+\.\d+\.\d$') = Field(..., title='Version')
    status: Literal['failure'] = Field(..., title='Status')
