# generated by datamodel-codegen:
#   filename:  reply_success.schema.json
#   timestamp: 2025-03-19T13:34:53+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, constr


class QuantumHardwareDynamicData(BaseModel):
    pass


class GetDynamicReplySuccess(BaseModel):
    version: constr(pattern=r'^\d+\.\d+\.\d$') = Field(..., title='Version')
    status: Literal['success'] = Field(..., title='Status')
    payload: QuantumHardwareDynamicData = Field(
        ..., description='The return value(s) of the executed command.'
    )
