# generated by datamodel-codegen:
#   filename:  request.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class GetDynamicRequest(BaseModel):
    version: str = Field(..., pattern='^\\d+\\.\\d+\\.\\d$', title='Version')
    command: Literal['get_dynamic'] = Field(..., title='Command')
