# generated by datamodel-codegen:
#   filename:  request.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, constr


class GetDynamicRequest(BaseModel):
    version: constr(pattern=r'^\d+\.\d+\.\d$') = Field(..., title='Version')
    command: Literal['get_dynamic'] = Field(..., title='Command')
