# generated by datamodel-codegen:
#   filename:  PublishState.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field


class HWCSState(Enum):
    IDLE = 'IDLE'
    EXECUTING = 'EXECUTING'
    CALIBRATING = 'CALIBRATING'
    OFFLINE = 'OFFLINE'


class PublishStatePayloadSchema(BaseModel):
    timestamp: float = Field(
        ...,
        description='Timestamp of the instantiation of the message (return value of time.time())',
        examples=[1752241667.1091666],
        title='Timestamp',
    )
    state: HWCSState = Field(..., examples=['IDLE'])


class PublishState(BaseModel):
    command: Literal['publish_state'] = Field(
        ..., examples=['publish_state'], title='Command'
    )
    payload: PublishStatePayloadSchema = Field(
        ..., examples=[{'state': 'IDLE', 'timestamp': 1752241667.1091666}]
    )
