# generated by datamodel-codegen:
#   filename:  PublishState.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal, Optional

from pydantic import BaseModel, Field


class HWCSState(Enum):
    IDLE = 'IDLE'
    EXECUTING = 'EXECUTING'
    CALIBRATING = 'CALIBRATING'
    OFFLINE = 'OFFLINE'


class PublishStatePayloadSchema(BaseModel):
    timestamp: float = Field(
        ...,
        description='Timestamp of the instantiation of the message (return value of time.time())',
        title='Timestamp',
    )
    state: HWCSState


class PublishState(BaseModel):
    version: Optional[str] = Field(
        '0.2.0',
        description='Version of the message schema. Has been made optional to allow for moving to the new versioning scheme.',
        pattern='^\\d+\\.\\d+\\.\\d$',
        title='Version',
    )
    command: Literal['publish_state'] = Field(..., title='Command')
    payload: PublishStatePayloadSchema
