# generated by datamodel-codegen:
#   filename:  QuantumHardwareInitializeRequest.schema.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field


class QuantumHardwareInitializeRequest(BaseModel):
    session_id: UUID = Field(
        ...,
        description='An arbitrary string, filled in in the request, which is copied into the reply object.',
        title='Session Id',
    )
    command: Literal['initialize'] = Field(..., title='Command')
