# generated by datamodel-codegen:
#   filename:  QuantumHardwareTerminateRequest.schema.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field


class QuantumHardwareTerminateRequest(BaseModel):
    session_id: UUID = Field(
        ...,
        description='An arbitrary string, filled in in the request, which is copied into the reply object.',
        examples=['8e7e2b6c-2b3c-4d9f-8b12-6a4d9b1e3f5a'],
        title='Session Id',
    )
    command: Literal['terminate'] = Field(..., examples=['terminate'], title='Command')
