# generated by datamodel-codegen:
#   filename:  QuantumHardwareDynamicDataRequest.schema.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field


class QuantumHardwareDynamicDataRequest(BaseModel):
    command: Literal['get_dynamic'] = Field(..., title='Command')
    session_id: UUID = Field(..., title='Session Id')
