# generated by datamodel-codegen:
#   filename:  QuantumHardwareDynamicDataResponse.schema.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class DynamicDataSchema(BaseModel):
    pass
    model_config = ConfigDict(
        extra='allow',
    )


class QuantumHardwareDynamicDataResponse(BaseModel):
    status: Literal['success'] = Field(..., examples=['success'], title='Status')
    payload: DynamicDataSchema = Field(
        ..., examples=[{'dynamic_key_1': 'dynamic_value_1'}]
    )
    session_id: UUID = Field(
        ..., examples=['8e7e2b6c-2b3c-4d9f-8b12-6a4d9b1e3f5a'], title='Session Id'
    )
