# generated by datamodel-codegen:
#   filename:  QuantumHardwareStaticDataRequest.schema.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field


class QuantumHardwareStaticDataRequest(BaseModel):
    command: Literal['get_static'] = Field(
        ..., examples=['get_static'], title='Command'
    )
    session_id: UUID = Field(
        ..., examples=['8e7e2b6c-2b3c-4d9f-8b12-6a4d9b1e3f5a'], title='Session Id'
    )
