# generated by datamodel-codegen:
#   filename:  QuantumHardwareStaticDataResponse.schema.json

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional
from uuid import UUID

from pydantic import BaseModel, Field, RootModel


class CompilerPass(BaseModel):
    path: str = Field(
        ...,
        description='Path to OpenSquirrel object that does the compiler pass',
        examples=['opensquirrel.passes.decomposer.mckay_decomposer.McKayDecomposer'],
        title='Path',
    )
    method: str = Field(
        ...,
        description='Method on OpenSquirrel object that does the compiler pass',
        examples=['decompose'],
        title='Method',
    )
    arguments: Optional[Dict[str, Any]] = Field(
        {},
        description='Arguments for the compiler pass',
        examples=[{}],
        title='Arguments',
    )


class TopologyItem(RootModel[List]):
    root: List = Field(..., max_length=2, min_length=2)


class Topology(RootModel[List[TopologyItem]]):
    root: List[TopologyItem] = Field(
        ...,
        description='A class representing the topology of a quantum chip.\n\nIt is a list of tuples, where each tuple represents a unidirectional connection between two qubits. The first\nelement of the tuple is the source qubit, and the second element is the target qubit.',
        title='Topology',
    )


class CompilerConfig(BaseModel):
    decomposition: Optional[List[CompilerPass]] = Field(
        [],
        description='The decomposition stage compiler config',
        examples=[
            [
                {
                    'arguments': {},
                    'method': 'decompose',
                    'path': 'opensquirrel.passes.decomposer.mckay_decomposer.McKayDecomposer',
                }
            ]
        ],
        title='Decomposition',
    )
    mapping: Optional[List[CompilerPass]] = Field(
        [],
        description='The mapping stage compiler config',
        examples=[
            [
                {
                    'arguments': {},
                    'method': 'decompose',
                    'path': 'opensquirrel.passes.decomposer.mckay_decomposer.McKayDecomposer',
                }
            ]
        ],
        title='Mapping',
    )
    optimization: Optional[List[CompilerPass]] = Field(
        [],
        description='The optimization stage compiler config',
        examples=[
            [
                {
                    'arguments': {},
                    'method': 'decompose',
                    'path': 'opensquirrel.passes.decomposer.mckay_decomposer.McKayDecomposer',
                }
            ]
        ],
        title='Optimization',
    )
    routing: Optional[List[CompilerPass]] = Field(
        [],
        description='The routing stage compiler config',
        examples=[
            [
                {
                    'arguments': {},
                    'method': 'decompose',
                    'path': 'opensquirrel.passes.decomposer.mckay_decomposer.McKayDecomposer',
                }
            ]
        ],
        title='Routing',
    )


class StaticDataSchema(BaseModel):
    protocol_version: Literal[3] = Field(..., examples=[3], title='Protocol Version')
    nqubits: int = Field(
        ..., description='The number of qubits.', examples=[3], title='Nqubits'
    )
    topology: Topology = Field(
        ...,
        description='List of the edges between the various qubits',
        examples=[[[0, 1], [1, 2], [2, 0], [3, 2]]],
    )
    name: str = Field(
        ..., description='Name of the system.', examples=['Spin2'], title='Name'
    )
    pgs: List[str] = Field(
        ...,
        description='Supported primitive gates set of the system. Gate names as described in cQASM (in uppercase).',
        examples=[['X', 'Y', 'Z']],
        title='Pgs',
    )
    default_compiler_config: Optional[CompilerConfig] = Field(
        default_factory=lambda: CompilerConfig.model_validate(
            {'decomposition': [], 'mapping': [], 'optimization': [], 'routing': []}
        ),
        description='A suitable default compiler configuration for the hardware backend',
        examples=[
            {
                'decomposition': [
                    {
                        'arguments': {},
                        'method': 'decompose',
                        'path': 'opensquirrel.passes.decomposer.mckay_decomposer.McKayDecomposer',
                    }
                ],
                'mapping': [
                    {
                        'arguments': {},
                        'method': 'decompose',
                        'path': 'opensquirrel.passes.decomposer.mckay_decomposer.McKayDecomposer',
                    }
                ],
                'optimization': [
                    {
                        'arguments': {},
                        'method': 'decompose',
                        'path': 'opensquirrel.passes.decomposer.mckay_decomposer.McKayDecomposer',
                    }
                ],
                'routing': [
                    {
                        'arguments': {},
                        'method': 'decompose',
                        'path': 'opensquirrel.passes.decomposer.mckay_decomposer.McKayDecomposer',
                    }
                ],
            }
        ],
    )
    starttime: float = Field(
        ...,
        description='Timestamp of start-up of the system (return value of time.time())',
        examples=[1752241667.1091666],
        title='Starttime',
    )
    supports_raw_data: Optional[bool] = Field(
        False,
        description='Whether the hardware backend supports shot memory. If True, the include_raw_data flag in the QuantumHardwareRunCircuitPayload should trigger the backend to store shot memory in the raw_data field of the results.',
        examples=[False],
        title='Supports Raw Data',
    )


class QuantumHardwareStaticDataResponse(BaseModel):
    status: Literal['success'] = Field(..., examples=['success'], title='Status')
    session_id: UUID = Field(
        ..., examples=['8e7e2b6c-2b3c-4d9f-8b12-6a4d9b1e3f5a'], title='Session Id'
    )
    payload: StaticDataSchema = Field(
        ...,
        examples=[
            {
                'default_compiler_config': {
                    'decomposition': [
                        {
                            'arguments': {},
                            'method': 'decompose',
                            'path': 'opensquirrel.passes.decomposer.mckay_decomposer.McKayDecomposer',
                        }
                    ],
                    'mapping': [
                        {
                            'arguments': {},
                            'method': 'decompose',
                            'path': 'opensquirrel.passes.decomposer.mckay_decomposer.McKayDecomposer',
                        }
                    ],
                    'optimization': [
                        {
                            'arguments': {},
                            'method': 'decompose',
                            'path': 'opensquirrel.passes.decomposer.mckay_decomposer.McKayDecomposer',
                        }
                    ],
                    'routing': [
                        {
                            'arguments': {},
                            'method': 'decompose',
                            'path': 'opensquirrel.passes.decomposer.mckay_decomposer.McKayDecomposer',
                        }
                    ],
                },
                'name': 'Spin2',
                'nqubits': 3,
                'pgs': ['X', 'Y', 'Z'],
                'protocol_version': 3,
                'starttime': 1752241667.1091666,
                'supports_raw_data': False,
                'topology': [[0, 1], [1, 2], [2, 0], [3, 2]],
            }
        ],
    )
