# generated by datamodel-codegen:
#   filename:  QuantumHardwareDynamicDataResponse.schema.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class DynamicDataSchema(BaseModel):
    pass
    model_config = ConfigDict(
        extra='allow',
    )


class QuantumHardwareDynamicDataResponse(BaseModel):
    status: Literal['success'] = Field(..., title='Status')
    payload: DynamicDataSchema
    session_id: UUID = Field(..., title='Session Id')
