# generated by datamodel-codegen:
#   filename:  reply_success.schema.json
#   timestamp: 2025-03-19T13:34:53+00:00

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field, constr


class TerminateReplySuccess(BaseModel):
    version: constr(pattern=r'^\d+\.\d+\.\d$') = Field(..., title='Version')
    session_id: UUID = Field(
        ...,
        description='An arbitrary string, filled in in the request, which is copied into the reply object.',
        title='Session Id',
    )
    status: Literal['success'] = Field(..., title='Status')
