# generated by datamodel-codegen:
#   filename:  QuantumHardwareDynamicDataRequest.schema.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field


class V2QuantumHardwareDynamicDataRequest(BaseModel):
    version: str = Field(..., pattern='^\\d+\\.\\d+\\.\\d$', title='Version')
    command: Literal['get_dynamic'] = Field(..., title='Command')
    session_id: UUID = Field(..., title='Session Id')
