# generated by datamodel-codegen:
#   filename:  QuantumHardwareTerminateRequest.schema.json

from __future__ import annotations

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field


class V2QuantumHardwareTerminateRequest(BaseModel):
    version: str = Field(..., pattern='^\\d+\\.\\d+\\.\\d$', title='Version')
    session_id: UUID = Field(
        ...,
        description='An arbitrary string, filled in in the request, which is copied into the reply object.',
        title='Session Id',
    )
    command: Literal['terminate'] = Field(..., title='Command')
