# generated by datamodel-codegen:
#   filename:  QuantumHardwareDynamicDataResponse.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class DynamicDataSchema(BaseModel):
    pass
    model_config = ConfigDict(
        extra='allow',
    )


class V2QuantumHardwareDynamicDataResponse(BaseModel):
    version: str = Field(..., pattern='^\\d+\\.\\d+\\.\\d$', title='Version')
    status: Literal['success'] = Field(..., title='Status')
    payload: DynamicDataSchema
