name: Linting

on:
  pull_request:

jobs:
  lint:
    name: Markdown linting
    runs-on: ubuntu-latest
    steps:
      - uses: DavidAnson/markdownlint-cli2-action@v11
        with:
          config: ".markdownlint-cli2.jsonc"
