name: Validation

on:
  pull_request:

jobs:
  lint:
    name: Markdown linting
    runs-on: ubuntu-latest
    steps:
      - uses: DavidAnson/markdownlint-cli2-action@v11
  schema-check:
    name: JSON validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        working-directory: ./tests/schema-check
        run: pip install -r requirements.txt
      - name: Run test cases
        working-directory: ./tests/schema-check
        run: ./tests.sh
  model-generation:
    name: Model generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        working-directory: ./tests/control-software-validator
        run: pip install -r requirements.txt
      - name: Run generator
        working-directory: ./tests/control-software-validator
        run: ./generate.sh
      - name: Verify files are unchanged
        run: git diff --exit-code
      - name: MyPy
        # Helps ensure changes in model classes are reflected in validator
        working-directory: ./tests/control-software-validator
        run: mypy .
      - name: Validator dry run
        working-directory: ./tests/control-software-validator
        run: CSV_MODE=dry_run pytest .
