name: Validation

on:
  pull_request:

jobs:
  lint:
    name: Markdown linting
    runs-on: ubuntu-latest
    steps:
      - uses: DavidAnson/markdownlint-cli2-action@v11
  tests:
    name: JSON validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        working-directory: ./tests/schema-check
        run: pip install -r requirements.txt
      - name: Run test cases
        working-directory: ./tests/schema-check
        run: ./tests.sh
